apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openclaw.fullname" . }}-data
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
